import Head from "next/head";
import Image from "next/image";
import { useState, useRef, useEffect } from "react";
import CopyToClipboard from "react-copy-to-clipboard";
import styles from "../styles/Home.module.css";

export default function Home() {
  const availablePlayers = [
    {
      name: "BatukkMaharajj",
      alias: "batuk",
      discord: "shivenjalan#4500",
      characterId: "61261413914",
    },
    {
      name: "BRT×M4",
      alias: "mohit",
      discord: "mycroft0307#0492",
      characterId: "5197623184",
    },
    {
      name: "4TD๛JøkëR",
      alias: "joker",
      discord: "4TDJoker#1431",
      characterId: "588361221",
    },
    {
      name: "BRT×Bandya",
      alias: "bandya",
      discord: "KINGPRAKASH#8961",
      characterId: "61322283687",
    },
    {
      name: "BRT×Paaji",
      alias: "paaji",
      discord: "Foxtrot#6979",
      characterId: "5760265396",
    },
    {
      name: "DârK×LeTHaL",
      alias: "lethal",
      discord: "Varun#1260",
      characterId: "51457034819",
    },
    {
      name: "BRT×MONK",
      alias: "monk",
      discord: "BRT oldmonk#1276",
      characterId: "581050663",
    },
    {
      name: "बंटासोड़",
      alias: "banta",
      discord: "Tushar#7966",
      characterId: "580908654",
    },
  ];

  const [names, setNames] = useState("");
  const [teamName, setTeamName] = useState("");
  const [showPlayers, setShowPlayers] = useState(false);
  const [playingTeam, setPlayingTeam] = useState([]);
  const [format, setFormat] = useState("");

  useEffect(() => {
    formatPlayers();
  }, [format, playingTeam]);

  const btnRef = useRef(null);

  const createTeam = () => {
    let players = names.split(" ");

    let playingPlayers = [];

    players.map((player) => {
      availablePlayers.map((ap) => {
        if (player.toLowerCase() === ap.alias.toLowerCase()) {
          playingPlayers.push(ap);
        }
      });
    });

    setPlayingTeam(playingPlayers);
    formatPlayers();
    setShowPlayers(true);

    // console.log(playingPlayers);
  };
  const handleButtonText = () => {
    btnRef.current.style.backgroundColor = "#10B981";
    btnRef.current.innerText = "Copied!";
  };
  const formatPlayers = () => {
    let str = "";

    str = str + "Team Name: " + teamName + "\n\n";

    playingTeam.forEach((player) => {
      str = str + "IGN: " + player.name + "\n";
      str = str + "Discord: " + player.discord + "\n";
      str = str + "CharacterID: " + player.characterId + "\n";
      str = str + "\n\n";
    });

    setFormat(str);
    // console.log("format =>", format);
    // console.log("STR =>", str);
  };

  const PlayersBox = ({ playingTeam, teamName, text }) => {
    console.log("TEXT: ", text);
    return (
      <>
        <div className="players-box">
          <CopyToClipboard text={text}>
            <button onClick={handleButtonText} ref={btnRef}>
              Copy Team
            </button>
          </CopyToClipboard>
          <p>
            <strong>Team Name: </strong>
            {teamName}
          </p>
          <br />

          {playingTeam.map((player, idx) => (
            <div key={idx}>
              <p>
                <strong>IGN: </strong> {player.name}
              </p>
              <p>
                <strong>Discord Tag:</strong> {player.discord}
              </p>
              <p>
                <strong>Character ID: </strong> {player.characterId}
              </p>
              <br />
            </div>
          ))}
        </div>
      </>
    );
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter") {
      createTeam();
    }
  };

  console.log("FORMAT", format);

  return (
    <div className="main">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <label htmlFor="teamName">Enter Team Name &nbsp;</label>
          <input
            type="text"
            name="teamName"
            placeholder="Enter Team Name"
            onChange={(e) => setTeamName(e.target.value)}
          />
        </div>
        <div>
          <label htmlFor="names">Enter Players &nbsp;</label>
          <input
            type="text"
            name="names"
            placeholder="Enter names, separate by space, max allowed - 5"
            onChange={(e) => setNames(e.target.value)}
            onKeyDown={(e) => handleKeyDown(e)}
          />
        </div>
        <button onClick={createTeam}>Create Team</button>

        {showPlayers && (
          // <PlayersBox
          //   playingTeam={playingTeam}
          //   teamName={teamName}
          //   text={format}
          // />
          <div className="players-box">
            <CopyToClipboard text={format}>
              <button onClick={handleButtonText} ref={btnRef}>
                Copy Team
              </button>
            </CopyToClipboard>
            <p>
              <strong>Team Name: </strong>
              {teamName}
            </p>
            <br />

            {playingTeam.map((player, idx) => (
              <div key={idx}>
                <p>
                  <strong>IGN: </strong> {player.name}
                </p>
                <p>
                  <strong>Discord Tag:</strong> {player.discord}
                </p>
                <p>
                  <strong>Character ID: </strong> {player.characterId}
                </p>
                <br />
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
